spring:
  application:
    name: ssis-ch10-ex3
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_1?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9103
