spring:
  application:
    name: ssis-ch07-ex1
server:
  port: 8120
logging:
  level:
    com.woojang.service.ch06ex1.repositories.UserRepository.findUserByUsername: DEBUG
    org:
      springframework:
        security: DEBUG
