spring:
  application:
    name: ssis-ch08-ex2
server:
  port: 8182
logging:
  level:
    com.woojang.service.ch06ex1.repositories.UserRepository.findUserByUsername: DEBUG
    org:
      springframework:
        security: DEBUG
